MyFirstProjectDjango/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^', include('landing.urls')),
                  url(r'^', include('products.urls')),
                  url(r'^', include('orders.urls'))

              ] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from landing import views

urlpatterns=[
   # path('landing/', views.landing, name='landing')
]

products/urls.py
from django.conf.urls import url
from django.urls import path
from products import views

urlpatterns = [
    url(r'^product/(?P<product_id>\w+)/$', views.product, name='product')
    # path('product/<product_id>', views.landing, name='landing')
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        """Sets the parameters for displaying user data in the admin panel."""
        return "Product: %s" % self.name

    class Meta:
        """Specifies the plural or singular"""
        verbose_name = "Category of product"
        verbose_name_plural = "Category of products"


class Product(models.Model):
    """Create model of Product"""
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_active = models.BooleanField(default=True)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete = models.DO_NOTHING)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        """Sets the parameters for displaying user data in the admin panel."""
        return "Product: %s" % self.name

    class Meta:
        """Specifies the plural or singular"""
        verbose_name = "Product"
        verbose_name_plural = "Products"


class ProductImages(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.DO_NOTHING)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        """Sets the parameters for displaying user data in the admin panel."""
        return "Product: %s" % self.id

    class Meta:
        """Specifies the plural or singular"""
        verbose_name = "Photo"
        verbose_name_plural = "Photos"

products/forms.py
from django import forms
from .models import *


# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = [""]

products/views.py
from django.shortcuts import render
from products.models import *


def product(request, product_id):
    product = Product.objects.get(id=product_id)
    return render(request, 'products/product.html', locals())

templates/products/product.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
   <div class="container">
       <div class="row">
           <div class="col-lg-6">
               {% for image_item in product.productimages_set.all %}
                   <img src="{{ image_item.image.url }}" class="img-responsive">
               {% endfor %}
           </div>
           <div class="col-lg-6">
               <h1 class="text-center">
                   {{ product.name }}
               </h1>
               <div class="">
                   <p>
                       {{ product.price }}
                   </p>
               </div>
               <div class="">
                   <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
                        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
                        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
                        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="home">ййй</div>
                        <div role="tabpanel" class="tab-pane" id="profile">ццц</div>
                        <div role="tabpanel" class="tab-pane" id="messages">...</div>
                        <div role="tabpanel" class="tab-pane" id="settings">...</div>
                      </div>
                    </div>
               </div>
           </div>
       </div>
   </div>
{% endblock content %}